# WARNING: This file is auto-generated by gen_tests.py
# Do not edit manually. Changes will be overwritten on each generation.

const SUITES := [
	"res://tests/test_OcctlBool.gd"
	"res://tests/test_OcctlCore.gd"
	"res://tests/test_OcctlCurves.gd"
	"res://tests/test_OcctlCurves2d.gd"
	"res://tests/test_OcctlCurvesCommon.gd"
	"res://tests/test_OcctlDe.gd"
	"res://tests/test_OcctlGeom.gd"
	"res://tests/test_OcctlHeal.gd"
	"res://tests/test_OcctlIoBrep.gd"
	"res://tests/test_OcctlIoGltf.gd"
	"res://tests/test_OcctlIoIges.gd"
	"res://tests/test_OcctlIoObj.gd"
	"res://tests/test_OcctlIoPly.gd"
	"res://tests/test_OcctlIoStep.gd"
	"res://tests/test_OcctlIoStl.gd"
	"res://tests/test_OcctlIoVrml.gd"
	"res://tests/test_OcctlMesh.gd"
	"res://tests/test_OcctlPrim.gd"
	"res://tests/test_OcctlPrimFeature.gd"
	"res://tests/test_OcctlPrimSketch.gd"
	"res://tests/test_OcctlPrimSolid.gd"
	"res://tests/test_OcctlPrimSweep.gd"
	"res://tests/test_OcctlSurfaces.gd"
	"res://tests/test_OcctlText.gd"
	"res://tests/test_OcctlTopo.gd"
	"res://tests/test_OcctlTopoAlgo.gd"
	"res://tests/test_OcctlTopoBuild.gd"
	"res://tests/test_OcctlTopoRelation.gd"
	"res://tests/test_OcctlTopoTypes.gd",
]
