// ---------------------------------------------------------------------------
// This file was auto-generated by the OCCT-Light.gd-autowrapper.
// DO NOT EDIT IT DIRECTLY. Make changes to the Python generator instead.
// ---------------------------------------------------------------------------

#ifndef OCLGRAPHHANDLE_H
#define OCLGRAPHHANDLE_H

#include <godot_cpp/classes/array_mesh.hpp>
#include <godot_cpp/classes/multi_mesh.hpp>
#include <godot_cpp/classes/ref.hpp>
#include <godot_cpp/core/class_db.hpp>
#include <godot_cpp/variant/utility_functions.hpp>
#include <cstdint>
#include "occtl/occtl_curves.h"
#include "occtl/occtl_topo.h"

#include "OclMeshOptions.h"

using namespace godot;

class OclGraphHandle : public godot::RefCounted {
    GDCLASS(OclGraphHandle, godot::RefCounted)
protected:
    static void _bind_methods();

    // Track the last deflection and angle used for face mesh generation.
    // The C triangulation view stores deflection but not angle, so we cache
    // both here to invalidate the cache when parameters change.
    double _last_mesh_deflection = -1.0;
    double _last_mesh_angle = -1.0;

public:
    occtl_graph_t* _handle = nullptr;
    bool _owns = true;

    ~OclGraphHandle() {
        if (_owns && _handle) {
            ::occtl_graph_free(_handle);
            _handle = nullptr;
        }
    }

    void set_handle(int64_t h);
    int64_t get_handle() const;
    bool is_valid() const;
    int64_t release();
    void free();

    // --- Meshing methods ---

    /// Triangulate faces into an ArrayMesh, or create collision shapes on a PhysicsBody3D.
    /// @param face_ids   Nil for all faces, or a PackedInt64Array of face node IDs.
    /// @param include_normals     Compute angle-thresholded smooth normals.
    /// @param include_uvs         Include UV coordinates if available.
    /// @param include_tangents    Compute tangent vectors (requires normals + UVs).
    /// @param include_feature_ids Encode face node IDs as vertex colors.
    /// @param options             Meshing options (deflection, angle, ...).
    ///                            When null, OCL_MESH_OPTIONS_INIT defaults are used.
    /// @param existing            Optional ArrayMesh, MultiMesh, or PhysicsBody3D to reuse.
    ///                            - ArrayMesh: surfaces cleared, user customizations preserved.
    ///                            - PhysicsBody3D: one ConcavePolygonShape3D child per face
    ///                              with metadata key "feature_id" mapping to the face node ID.
    ///                            - Null/nil: a fresh ArrayMesh is created.
    Ref<ArrayMesh> mesh_faces(
        const Variant& face_ids = Variant(),
        bool include_normals = false,
        bool include_uvs = false,
        bool include_tangents = false,
        bool include_feature_ids = false,
        const Ref<OclMeshOptions>& options = Ref<OclMeshOptions>(),
        const Variant& existing = Variant()
    );

    /// Build edge tube instances as a MultiMesh, or create collision shapes on a PhysicsBody3D.
    /// A low-resolution cylinder mesh is instanced along each edge polyline
    /// segment using MultiMesh transforms.
    /// @param edge_ids  Nil for all edges, or a PackedInt64Array of edge node IDs.
    /// @param radius    Tube radius.  <= 0 uses opts.deflection * 10.
    /// @param options   Meshing options (controls cylinder resolution via angle).
    /// @param existing  Optional MultiMesh or PhysicsBody3D to reuse.
    ///                  - MultiMesh: mesh+transforms replaced, user customizations preserved.
    ///                  - PhysicsBody3D: one CylinderShape3D child per segment
    ///                    with metadata key "feature_id" mapping to the edge node ID.
    ///                  - Null/nil: a fresh MultiMesh is created.
    Ref<MultiMesh> mesh_edges(
        const Variant& edge_ids = Variant(),
        double radius = 0.01,
        const Ref<OclMeshOptions>& options = Ref<OclMeshOptions>(),
        const Variant& existing = Variant()
    );

    /// Build vertex sphere instances as a MultiMesh, or create collision shapes on a PhysicsBody3D.
    /// A low-resolution sphere mesh is instanced at each vertex position.
    /// @param vertex_ids  Nil for all vertices, or a PackedInt64Array of vertex IDs.
    /// @param radius      Sphere radius.  <= 0 uses opts.deflection * 10.
    /// @param options     Meshing options (controls sphere resolution via angle).
    /// @param existing    Optional MultiMesh or PhysicsBody3D to reuse.
    ///                    - MultiMesh: mesh+transforms replaced, user customizations preserved.
    ///                    - PhysicsBody3D: one SphereShape3D child per vertex
    ///                      with metadata key "feature_id" mapping to the vertex node ID.
    ///                    - Null/nil: a fresh MultiMesh is created.
    Ref<MultiMesh> mesh_vertices(
        const Variant& vertex_ids = Variant(),
        double radius = 0.02,
        const Ref<OclMeshOptions>& options = Ref<OclMeshOptions>(),
        const Variant& existing = Variant()
    );
};

#endif // OCLGRAPHHANDLE_H
