class_name TestOcctlGraphHandle

# ---------------------------------------------------------------------------
# This file was auto-generated by the OCCT-Light.gd-autowrapper.
# DO NOT EDIT IT DIRECTLY. Make changes to the Python generator instead.
# ---------------------------------------------------------------------------

# ---------------------------------------------------------------------------
# Helper functions
# ---------------------------------------------------------------------------

static func _collect_node_kind_ids(graph, kind: int) -> Array:
	var topo = OcctlTopo.new()
	var ids = []
	var iter: OcctlNodeIterHandle
	match kind:
		OcctlCore.OCCTL_KIND_SOLID:
			iter = topo.graph_solid_iter_create(graph)
		OcctlCore.OCCTL_KIND_SHELL:
			iter = topo.graph_shell_iter_create(graph)
		OcctlCore.OCCTL_KIND_FACE:
			iter = topo.graph_face_iter_create(graph)
		OcctlCore.OCCTL_KIND_WIRE:
			iter = topo.graph_wire_iter_create(graph)
		OcctlCore.OCCTL_KIND_EDGE:
			iter = topo.graph_edge_iter_create(graph)
		OcctlCore.OCCTL_KIND_VERTEX:
			iter = topo.graph_vertex_iter_create(graph)
		OcctlCore.OCCTL_KIND_COMPOUND:
			iter = topo.graph_compound_iter_create(graph)
		OcctlCore.OCCTL_KIND_COMPSOLID:
			iter = topo.graph_compsolid_iter_create(graph)
		OcctlCore.OCCTL_KIND_COEDGE:
			iter = topo.graph_coedge_iter_create(graph)
		_:
			return []
	if iter == null:
		return []
	var out_id = OcctlNodeId.new()
	while true:
		var status = topo.node_iter_next(iter, out_id)
		if status != 0:
			break
		ids.append(out_id.get_bits())
	return ids

static func _make_box_graph() -> Dictionary:
	var core = OcctlCore.new()
	var rt_status = core.runtime_init()
	# OCCTL_INVALID_ARGUMENT (2) = runtime already initialized — not a fatal error
	if rt_status != 0 and rt_status != 2:
		return {"error": "runtime_init failed: %d" % rt_status}

	var topo = OcctlTopo.new()
	var graph = topo.graph_create()
	if graph == null:
		return {"error": "graph_create returned null"}

	var prim = OcctlPrimSolid.new()
	var info = OcctlPrimBoxInfo.new()
	prim.box_info_init(info)
	info.set_dx(10.0)
	info.set_dy(20.0)
	info.set_dz(30.0)

	var box_root = OcctlNodeId.new()
	var status = prim.make_box(graph, info, box_root)
	if status != 0:
		return {"error": "make_box failed: %d" % status}

	return {"graph": graph, "root": box_root, "core": core}

# ---------------------------------------------------------------------------
# Mesh batch methods — edge cases (null/invalid graph)
# ---------------------------------------------------------------------------

static func test_mesh_faces_null_graph() -> String:
	var graph = OcctlGraphHandle.new()
	# Graph handle is null — should return empty ArrayMesh
	var mesh = graph.mesh_faces()
	if mesh == null:
		return "expected non-null ArrayMesh, got null"
	if mesh.get_surface_count() != 0:
		return "expected 0 surfaces for null graph, got %d" % mesh.get_surface_count()
	return ""

static func test_mesh_faces_reuse_existing() -> String:
	var graph = OcctlGraphHandle.new()
	var existing = ArrayMesh.new()
	# Add a dummy surface to verify it gets cleared
	var dummy_arr = []
	dummy_arr.resize(Mesh.ARRAY_MAX)
	var verts = PackedVector3Array([Vector3(0,0,0), Vector3(1,0,0), Vector3(0,1,0)])
	dummy_arr[Mesh.ARRAY_VERTEX] = verts
	var idxs = PackedInt32Array([0, 1, 2])
	dummy_arr[Mesh.ARRAY_INDEX] = idxs
	existing.add_surface_from_arrays(Mesh.PRIMITIVE_TRIANGLES, dummy_arr)
	if existing.get_surface_count() != 1:
		return "expected 1 dummy surface before reuse"

	var result = graph.mesh_faces([], false, false, false, false, null, existing)
	if result != existing:
		return "expected same ArrayMesh object back"
	# Should be cleared (no surfaces due to empty face_ids)
	if result.get_surface_count() != 0:
		return "expected 0 surfaces after clear with no ids, got %d" % result.get_surface_count()
	return ""

static func test_mesh_edges_null_graph() -> String:
	var graph = OcctlGraphHandle.new()
	var mm = graph.mesh_edges()
	if mm == null:
		return "expected non-null MultiMesh, got null"
	if mm.get_instance_count() != 0:
		return "expected 0 instances for null graph, got %d" % mm.get_instance_count()
	return ""

static func test_mesh_edges_reuse_existing() -> String:
	var graph = OcctlGraphHandle.new()
	var mm = MultiMesh.new()
	mm.set_instance_count(5)
	var result = graph.mesh_edges([], 0.01, null, mm)
	if result != mm:
		return "expected same MultiMesh object back"
	if result.get_instance_count() != 0:
		return "expected 0 instances after clear"
	return ""

static func test_mesh_vertices_null_graph() -> String:
	var graph = OcctlGraphHandle.new()
	var mm = graph.mesh_vertices()
	if mm == null:
		return "expected non-null MultiMesh, got null"
	if mm.get_instance_count() != 0:
		return "expected 0 instances for null graph, got %d" % mm.get_instance_count()
	return ""

static func test_mesh_vertices_reuse_existing() -> String:
	var graph = OcctlGraphHandle.new()
	var mm = MultiMesh.new()
	mm.set_instance_count(5)
	var result = graph.mesh_vertices([], 0.02, null, mm)
	if result != mm:
		return "expected same MultiMesh object back"
	if result.get_instance_count() != 0:
		return "expected 0 instances after clear"
	return ""

# ---------------------------------------------------------------------------
# Mesh batch methods — integration tests
# Creates a box solid, then tests faces/edges/vertices meshing
# ---------------------------------------------------------------------------

static func test_mesh_faces_with_box() -> String:
	var result = _make_box_graph()
	if result.has("error"):
		return result.error

	var graph: OcctlGraphHandle = result.graph

	# Test with all attributes enabled and explicit mesh options
	var mw = OcctlMesh.new()
	var mesh_opts = OcctlMeshOptions.new()
	mw.options_init(mesh_opts)
	mesh_opts.set_deflection(1.0)
	var root_id = PackedInt64Array([result.root.get_bits()])
	var mesh_status = mw.generate(graph, root_id, mesh_opts)
	if mesh_status != 0:
		return "mesh generate failed: %d" % mesh_status

	var face_ids = _collect_node_kind_ids(graph, OcctlCore.OCCTL_KIND_FACE)
	if face_ids.size() == 0:
		return "no faces found in box graph"

	var mesh = graph.mesh_faces(PackedInt64Array(face_ids),
		true, true, true, true, mesh_opts)
	if mesh == null:
		return "mesh_faces returned null"
	if mesh.get_surface_count() == 0:
		return "expected at least 1 surface, got 0"

	var surface_arrays = mesh.surface_get_arrays(0)
	if surface_arrays.size() <= Mesh.ARRAY_VERTEX:
		return "surface arrays too small"
	var verts = surface_arrays[Mesh.ARRAY_VERTEX] as PackedVector3Array
	if verts.size() == 0:
		return "expected non-empty vertex array"

	var has_normals = surface_arrays[Mesh.ARRAY_NORMAL] != null
	var has_uvs = surface_arrays[Mesh.ARRAY_TEX_UV] != null
	var has_tangents = surface_arrays[Mesh.ARRAY_TANGENT] != null
	var has_colors = surface_arrays[Mesh.ARRAY_COLOR] != null

	if not has_normals:
		return "expected normals (include_normals=true)"
	if not has_uvs:
		return "expected UVs (include_uvs=true)"
	if not has_tangents:
		return "expected tangents (include_tangents=true)"
	if not has_colors:
		return "expected feature ID colors (include_feature_ids=true)"

	return ""

static func test_mesh_faces_defaults_no_attributes() -> String:
	var result = _make_box_graph()
	if result.has("error"):
		return result.error

	var graph: OcctlGraphHandle = result.graph

	var mw = OcctlMesh.new()
	var mesh_opts = OcctlMeshOptions.new()
	mw.options_init(mesh_opts)
	mesh_opts.set_deflection(1.0)
	var root_id = PackedInt64Array([result.root.get_bits()])
	var mesh_status = mw.generate(graph, root_id, mesh_opts)
	if mesh_status != 0:
		return "mesh generate failed: %d" % mesh_status

	var face_ids = _collect_node_kind_ids(graph, OcctlCore.OCCTL_KIND_FACE)
	if face_ids.size() == 0:
		return "no faces found in box graph"

	# All attributes disabled by default for performance
	var mesh = graph.mesh_faces(PackedInt64Array(face_ids))
	if mesh == null:
		return "mesh_faces returned null"
	if mesh.get_surface_count() == 0:
		return "expected at least 1 surface, got 0"

	var surface_arrays = mesh.surface_get_arrays(0)
	var has_normals = surface_arrays[Mesh.ARRAY_NORMAL] != null
	var has_uvs = surface_arrays[Mesh.ARRAY_TEX_UV] != null
	var has_tangents = surface_arrays[Mesh.ARRAY_TANGENT] != null

	if has_normals:
		return "expected NO normals by default"
	if has_uvs:
		return "expected NO UVs by default"
	if has_tangents:
		return "expected NO tangents by default"

	return ""

static func test_mesh_edges_with_box() -> String:
	var result = _make_box_graph()
	if result.has("error"):
		return result.error

	var graph: OcctlGraphHandle = result.graph

	var mw = OcctlMesh.new()
	var mesh_opts = OcctlMeshOptions.new()
	mw.options_init(mesh_opts)
	mesh_opts.set_deflection(1.0)
	var root_id = PackedInt64Array([result.root.get_bits()])
	var mesh_status = mw.generate(graph, root_id, mesh_opts)
	if mesh_status != 0:
		return "mesh generate failed: %d" % mesh_status

	var edge_ids = _collect_node_kind_ids(graph, OcctlCore.OCCTL_KIND_EDGE)
	if edge_ids.size() == 0:
		return "no edges found in box graph"

	var mm = graph.mesh_edges(PackedInt64Array(edge_ids), 0.5, mesh_opts)
	if mm == null:
		return "mesh_edges returned null"
	if mm.get_instance_count() == 0:
		return "expected at least 1 instance, got 0"
	if mm.get_mesh() == null:
		return "expected a base cylinder mesh"

	return ""

static func test_mesh_vertices_with_box() -> String:
	var result = _make_box_graph()
	if result.has("error"):
		return result.error

	var graph: OcctlGraphHandle = result.graph

	var mw = OcctlMesh.new()
	var mesh_opts = OcctlMeshOptions.new()
	mw.options_init(mesh_opts)
	mesh_opts.set_deflection(1.0)
	var root_id = PackedInt64Array([result.root.get_bits()])
	var mesh_status = mw.generate(graph, root_id, mesh_opts)
	if mesh_status != 0:
		return "mesh generate failed: %d" % mesh_status

	var vert_ids = _collect_node_kind_ids(graph, OcctlCore.OCCTL_KIND_VERTEX)
	if vert_ids.size() == 0:
		return "no vertices found in box graph"

	var mm = graph.mesh_vertices(PackedInt64Array(vert_ids), 0.02, mesh_opts)
	if mm == null:
		return "mesh_vertices returned null"
	if mm.get_instance_count() == 0:
		return "expected at least 1 instance, got 0"
	if mm.get_mesh() == null:
		return "expected a base sphere mesh"

	return ""

# ---------------------------------------------------------------------------
# Bounding-box consistency: mesh_edges and mesh_vertices should use the
# graph-wide bbox via _get_graph_bbox_diag for consistent sizing.
# Since these are internal implementation details and we cannot call C
# functions directly from GDScript, we verify by calling both methods on
# the same graph and observing that the produced instances are reasonable.
# ---------------------------------------------------------------------------

static func test_mesh_bbox_consistency() -> String:
	var result = _make_box_graph()
	if result.has("error"):
		return result.error

	var graph: OcctlGraphHandle = result.graph

	var mw = OcctlMesh.new()
	var mesh_opts = OcctlMeshOptions.new()
	mw.options_init(mesh_opts)
	mesh_opts.set_deflection(1.0)
	var root_id = PackedInt64Array([result.root.get_bits()])
	var mesh_status = mw.generate(graph, root_id, mesh_opts)
	if mesh_status != 0:
		return "mesh generate failed: %d" % mesh_status

	# Both edge and vertex meshing should succeed with default radii on the same graph
	var edge_ids = _collect_node_kind_ids(graph, OcctlCore.OCCTL_KIND_EDGE)
	var vert_ids = _collect_node_kind_ids(graph, OcctlCore.OCCTL_KIND_VERTEX)

	if edge_ids.size() == 0:
		return "no edges found"

	var edge_mm = graph.mesh_edges(PackedInt64Array(edge_ids), 0.01, mesh_opts)
	if edge_mm == null:
		return "mesh_edges returned null"
	if edge_mm.get_instance_count() == 0:
		return "expected edge instances"

	if vert_ids.size() == 0:
		return "no vertices found"

	var vert_mm = graph.mesh_vertices(PackedInt64Array(vert_ids), 0.02, mesh_opts)
	if vert_mm == null:
		return "mesh_vertices returned null"
	if vert_mm.get_instance_count() == 0:
		return "expected vertex instances"

	return ""

# ---------------------------------------------------------------------------
# PhysicsBody3D collision shape tests
# ---------------------------------------------------------------------------

static func test_mesh_faces_physics_body() -> String:
	var result = _make_box_graph()
	if result.has("error"):
		return result.error

	var graph: OcctlGraphHandle = result.graph

	var mw = OcctlMesh.new()
	var mesh_opts = OcctlMeshOptions.new()
	mw.options_init(mesh_opts)
	mesh_opts.set_deflection(1.0)
	var root_id = PackedInt64Array([result.root.get_bits()])
	var mesh_status = mw.generate(graph, root_id, mesh_opts)
	if mesh_status != 0:
		return "mesh generate failed: %d" % mesh_status

	var face_ids = _collect_node_kind_ids(graph, OcctlCore.OCCTL_KIND_FACE)
	if face_ids.size() == 0:
		return "no faces found"

	var body = StaticBody3D.new()
	var ret = graph.mesh_faces(PackedInt64Array(face_ids), false, false, false, false, mesh_opts, body)
	# Should return null when using a PhysicsBody3D
	if ret != null:
		return "expected null return when passing PhysicsBody3D, got %s" % ret

	# Verify children were added
	if body.get_child_count() == 0:
		return "expected at least 1 CollisionShape3D child"
	# Check a child has occtl metadata
	var cs = body.get_child(0) as CollisionShape3D
	if cs == null:
		return "expected CollisionShape3D children"
	var meta = cs.get_meta("occtl") as Dictionary
	if meta == null or not meta.has("feature_id"):
		return "expected occtl metadata with feature_id"
	var shape = cs.get_shape()
	if shape == null:
		return "expected shape on CollisionShape3D"
	if not (shape is ConcavePolygonShape3D):
		return "expected ConcavePolygonShape3D for faces, got %s" % shape.get_class()
	return ""

static func test_mesh_edges_physics_body() -> String:
	var result = _make_box_graph()
	if result.has("error"):
		return result.error

	var graph: OcctlGraphHandle = result.graph

	var mw = OcctlMesh.new()
	var mesh_opts = OcctlMeshOptions.new()
	mw.options_init(mesh_opts)
	mesh_opts.set_deflection(1.0)
	var root_id = PackedInt64Array([result.root.get_bits()])
	var mesh_status = mw.generate(graph, root_id, mesh_opts)
	if mesh_status != 0:
		return "mesh generate failed: %d" % mesh_status

	var edge_ids = _collect_node_kind_ids(graph, OcctlCore.OCCTL_KIND_EDGE)
	if edge_ids.size() == 0:
		return "no edges found"

	var body = StaticBody3D.new()
	var ret = graph.mesh_edges(PackedInt64Array(edge_ids), 0.01, mesh_opts, body)
	if ret != null:
		return "expected null return when passing PhysicsBody3D"
	if body.get_child_count() == 0:
		return "expected at least 1 CollisionShape3D child"
	var cs = body.get_child(0) as CollisionShape3D
	if cs == null:
		return "expected CollisionShape3D children"
	var meta = cs.get_meta("occtl") as Dictionary
	if meta == null or not meta.has("feature_id"):
		return "expected occtl metadata with feature_id"
	var shape = cs.get_shape()
	if shape == null:
		return "expected shape on CollisionShape3D"
	if not (shape is CapsuleShape3D):
		return "expected CapsuleShape3D for edges, got %s" % shape.get_class()
	return ""

static func test_mesh_vertices_physics_body() -> String:
	var result = _make_box_graph()
	if result.has("error"):
		return result.error

	var graph: OcctlGraphHandle = result.graph

	var mw = OcctlMesh.new()
	var mesh_opts = OcctlMeshOptions.new()
	mw.options_init(mesh_opts)
	mesh_opts.set_deflection(1.0)
	var root_id = PackedInt64Array([result.root.get_bits()])
	var mesh_status = mw.generate(graph, root_id, mesh_opts)
	if mesh_status != 0:
		return "mesh generate failed: %d" % mesh_status

	var vert_ids = _collect_node_kind_ids(graph, OcctlCore.OCCTL_KIND_VERTEX)
	if vert_ids.size() == 0:
		return "no vertices found"

	var body = StaticBody3D.new()
	var ret = graph.mesh_vertices(PackedInt64Array(vert_ids), 0.02, mesh_opts, body)
	if ret != null:
		return "expected null return when passing PhysicsBody3D"
	if body.get_child_count() == 0:
		return "expected at least 1 CollisionShape3D child"
	var cs = body.get_child(0) as CollisionShape3D
	if cs == null:
		return "expected CollisionShape3D children"
	var meta = cs.get_meta("occtl") as Dictionary
	if meta == null or not meta.has("feature_id"):
		return "expected occtl metadata with feature_id"
	var shape = cs.get_shape()
	if shape == null:
		return "expected shape on CollisionShape3D"
	if not (shape is SphereShape3D):
		return "expected SphereShape3D for vertices, got %s" % shape.get_class()
	return ""

static func test_physics_body_reuse_clears_children() -> String:
	var result = _make_box_graph()
	if result.has("error"):
		return result.error

	var graph: OcctlGraphHandle = result.graph

	var mw = OcctlMesh.new()
	var mesh_opts = OcctlMeshOptions.new()
	mw.options_init(mesh_opts)
	mesh_opts.set_deflection(1.0)
	var root_id = PackedInt64Array([result.root.get_bits()])
	var mesh_status = mw.generate(graph, root_id, mesh_opts)
	if mesh_status != 0:
		return "mesh generate failed: %d" % mesh_status

	var edge_ids = _collect_node_kind_ids(graph, OcctlCore.OCCTL_KIND_EDGE)
	if edge_ids.size() == 0:
		return "no edges found"

	var body = StaticBody3D.new()
	# First call adds collision children
	graph.mesh_edges(PackedInt64Array(edge_ids), 0.01, mesh_opts, body)
	var first_count = body.get_child_count()
	if first_count == 0:
		return "expected children after first call"

	# Second call with same body should clear previous children and re-add
	graph.mesh_edges(PackedInt64Array(edge_ids), 0.01, mesh_opts, body)
	var second_count = body.get_child_count()
	if second_count != first_count:
		return "expected same number of children after reuse, got %d vs %d" % [second_count, first_count]

	return ""
