#ifndef GDEXT_MODULE_PARTS_H
#define GDEXT_MODULE_PARTS_H

#include <godot_cpp/godot.hpp>
#include <godot_cpp/core/class_db.hpp>

using namespace godot;

void gdext_initialize_module_part_0(ModuleInitializationLevel p_level);
void gdext_uninitialize_module_part_0(ModuleInitializationLevel p_level);
void gdext_initialize_module_part_1(ModuleInitializationLevel p_level);
void gdext_uninitialize_module_part_1(ModuleInitializationLevel p_level);
void gdext_initialize_module_part_2(ModuleInitializationLevel p_level);
void gdext_uninitialize_module_part_2(ModuleInitializationLevel p_level);
void gdext_initialize_module_part_3(ModuleInitializationLevel p_level);
void gdext_uninitialize_module_part_3(ModuleInitializationLevel p_level);
void gdext_initialize_module_part_4(ModuleInitializationLevel p_level);
void gdext_uninitialize_module_part_4(ModuleInitializationLevel p_level);
void gdext_initialize_module_part_5(ModuleInitializationLevel p_level);
void gdext_uninitialize_module_part_5(ModuleInitializationLevel p_level);
void gdext_initialize_module_part_6(ModuleInitializationLevel p_level);
void gdext_uninitialize_module_part_6(ModuleInitializationLevel p_level);
void gdext_initialize_module_part_7(ModuleInitializationLevel p_level);
void gdext_uninitialize_module_part_7(ModuleInitializationLevel p_level);

#endif // GDEXT_MODULE_PARTS_H
