"""Generate GDScript test files for autowrapper-generated classes.

Produces test files for wrapped functions (one per parsed header) and
handle classes (via template files in src/templates/).
An index.gd is generated referencing all test files.
"""

from pathlib import Path

from gen_handles import _template_path
from gen_wrapper import (
    _wrapper_class_name,
    generate_gdscript_tests,
)
from parser import CStruct, ParsedHeader
from type_map import HANDLE_TYPES, c_type_to_godot_class


def generate_all_tests(
    parsed_headers: list[ParsedHeader],
    output_dir: Path,
) -> list[str]:
    """Generate GDScript test files and index.gd.

    Writes to output_dir/demo/tests/ (or creates the directory).

    Returns list of filenames written.
    """
    tests_dir = output_dir / "demo" / "tests" / "autowrapper"
    tests_dir.mkdir(parents=True, exist_ok=True)
    tests_parent_dir = output_dir / "demo" / "tests"

    written: list[str] = []
    test_paths: list[str] = []

    for ph in parsed_headers:
        cls = _wrapper_class_name(ph.header_include)
        gdscript = generate_gdscript_tests(ph, cls)
        fname = f"test_{cls}.gd"
        (tests_dir / fname).write_text(gdscript)
        written.append(fname)
        test_paths.append(f"res://tests/autowrapper/{fname}")

    # Clean up orphan test files (no longer generated) — only in autowrapper subdir
    expected_tests = {
        f"test_{_wrapper_class_name(ph.header_include)}" for ph in parsed_headers
    }

    # Generate handle test files from templates (e.g. test_OclGraphHandle.gd)
    for c_type in HANDLE_TYPES:
        cls = c_type_to_godot_class(c_type) + "Handle"
        fname = f"test_{cls}.gd"
        tpath = _template_path(f"test_{cls}", "gd")
        if tpath:
            (tests_dir / fname).write_text(tpath.read_text())
            written.append(fname)
            test_paths.append(f"res://tests/autowrapper/{fname}")
            expected_tests.add(f"test_{cls}")

    # Clean up orphan test files in autowrapper subdirectory only
    for f in tests_dir.iterdir():
        if f.suffix == ".gd" and f.name != "index.gd" and "select_iter" not in f.name:
            if f.stem not in expected_tests:
                f.unlink()
                print(f"  [cleanup] removed orphan test: {f.name}")

    # Include hand-written manual test files if they exist (from parent tests dir)
    manual_tests = ["test_select_iter"]
    for mt in manual_tests:
        mt_file = tests_parent_dir / f"{mt}.gd"
        if mt_file.exists():
            test_paths.append(f"res://tests/{mt}.gd")

    # Write index.gd in the parent tests directory (not in autowrapper subdir)
    # This file is read by TestRunner at runtime.
    # NOTE: TestRunner also has a _try_regenerate_test_index() fallback for
    # exported builds, but in editor/dev builds this file is authoritative.
    suites_lines = "\n".join(f'\t"{p}",' for p in test_paths)
    index_content = (
        "# WARNING: This file is auto-generated by gen_tests.py.\n"
        "# Do not edit manually. Changes will be overwritten on each generation.\n"
        "\n"
        f"const SUITES := [\n{suites_lines}\n]\n"
    )
    index_file = tests_parent_dir / "index.gd"
    index_file.write_text(index_content)
    written.append("index.gd")

    return written
