"""Generate GDScript test files for autowrapper-generated classes.

Produces one test file per parsed header (using the wrapper's test generator)
and an index.gd that references all test files.
"""

from pathlib import Path

from gen_wrapper import (
    _wrapper_class_name,
    generate_gdscript_tests,
)
from parser import ParsedHeader


def generate_all_tests(
    parsed_headers: list[ParsedHeader],
    output_dir: Path,
) -> list[str]:
    """Generate GDScript test files and index.gd.

    Writes to output_dir/demo/tests/ (or creates the directory).

    Returns list of filenames written.
    """
    tests_dir = output_dir / "demo" / "tests"
    tests_dir.mkdir(parents=True, exist_ok=True)

    written: list[str] = []
    test_paths: list[str] = []

    for ph in parsed_headers:
        cls = _wrapper_class_name(ph.header_include)
        gdscript = generate_gdscript_tests(ph, cls)
        fname = f"test_{cls}.gd"
        (tests_dir / fname).write_text(gdscript)
        written.append(fname)
        test_paths.append(f"res://tests/{fname}")

    # Clean up orphan test files (no longer generated)
    expected_tests = {
        f"test_{_wrapper_class_name(ph.header_include)}" for ph in parsed_headers
    }
    expected_tests.add("test_select_iter")
    for f in tests_dir.iterdir():
        if f.suffix == ".gd" and f.stem.startswith("test_Occtl"):
            if f.stem not in expected_tests:
                f.unlink()
                print(f"  [cleanup] removed orphan test: {f.name}")

    # Include hand-written manual test files if they exist
    manual_tests = ["test_select_iter"]
    for mt in manual_tests:
        mt_file = tests_dir / f"{mt}.gd"
        if mt_file.exists():
            test_paths.append(f"res://tests/{mt}.gd")

    # Write index.gd
    suites_lines = "\n".join(f'\t"{p}"' for p in test_paths)
    index_content = (
        "# WARNING: This file is auto-generated by gen_tests.py\n"
        "# Do not edit manually. Changes will be overwritten on each generation.\n"
        "\n"
        f"const SUITES := [\n{suites_lines},\n]\n"
    )
    index_file = tests_dir / "index.gd"
    index_file.write_text(index_content)
    written.append("index.gd")

    return written
