"""Generate GDScript test files for autowrapper-generated classes.

Produces one test file per parsed header (using the wrapper's test generator)
and an index.gd that references all test files.
"""

from pathlib import Path

from gen_wrapper import (
    _wrapper_class_name,
    generate_gdscript_tests,
)
from parser import ParsedHeader


def generate_all_tests(
    parsed_headers: list[ParsedHeader],
    output_dir: Path,
) -> list[str]:
    """Generate GDScript test files and index.gd.

    Writes to output_dir/demo/tests/ (or creates the directory).

    Returns list of filenames written.
    """
    tests_dir = output_dir / "demo" / "tests"
    tests_dir.mkdir(parents=True, exist_ok=True)

    written: list[str] = []
    test_paths: list[str] = []

    for ph in parsed_headers:
        cls = _wrapper_class_name(ph.header_include)
        gdscript = generate_gdscript_tests(ph, cls)
        fname = f"test_{cls}.gd"
        (tests_dir / fname).write_text(gdscript)
        written.append(fname)
        test_paths.append(f'res://tests/{fname}')

    # Write index.gd
    suites_lines = ",\n".join(f'\t"{p}"' for p in test_paths)
    index_content = (
        "# WARNING: This file is auto-generated by gen_tests.py\n"
        "# Do not edit manually. Changes will be overwritten on each generation.\n"
        "\n"
        f"const SUITES := [\n{suites_lines},\n]\n"
    )
    index_file = tests_dir / "index.gd"
    index_file.write_text(index_content)
    written.append("index.gd")

    return written
